spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:mydb
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: create